### ISSUE TITLE
Simplify resetting current search

### ISSUE THREAD

**Issue by idoshamun** [dailydotdev/daily-apps#91]
We can expand our key bindings system developed by @sshanzel in #84, as follow:
* `esc` - should take the user back to the home page from the search page.

Discussed here:
https://github.com/dailydotdev/daily/issues/138

**Comment by sshanzel** [comment]
Gonna get started quickly!!! 😁

**Comment by sshanzel** [comment]
Hi Ido! I just realized, initially we made the keybinding feat centralized so keypress won't trigger 2 events at once, i think this might be contradicting with our first implementation, i've thought that this is much more applicable to be isolated on searchbars only. Since `esc` might be required to behave differently on different contexts as well. What do you think?

**Comment by idoshamun** [comment]
I would like to think of `esc` as the clear temporary filters and go back to home page button. It could be when you selected to see one source/tag, searched for something or even bookmarks. So we have many contexts that might be relevant. What do you think?

**Comment by sshanzel** [comment]
Totally makes sense! Thank you for the clarification!

**Comment by idoshamun** [comment]
Hi @sshanzel,
I would like to kindly check the status of this issue :)

**Comment by sshanzel** [comment]
Hi @idoshamun, I'm terribly sorry it took this long. I didn't realize i haven't had this yet. This was actually my planned contribution for April but i got loaded my day job. I've created the PR #111 for this, please let me know if you have any concern or issues on it. Thank you very much for understanding!
